const choice = (question, options, answer) => ({ question, options, answer });
const textQuestion = (question, answers) => ({ question, answers });

window.quizData = {
  prvouka: {
    title: "Prvouka pro 3. třídu",
    subtitle: "Příroda, člověk a svět kolem nás",
    description: "50 otázek od lehkých poznávaček až po těžší přemýšlení.",
    type: "choice",
    questions: [
      choice("Které roční období bývá nejteplejší?", ["jaro", "léto", "zima"], 1),
      choice("Kolik hodin má jeden den?", ["12", "24", "48"], 1),
      choice("Čím dýcháme?", ["plícemi", "uchem", "kolenem"], 0),
      choice("Které zvíře nám dává mléko?", ["kráva", "vrabec", "liška"], 0),
      choice("Kde žije kapr?", ["na stromě", "ve vodě", "v písku"], 1),
      choice("Který měsíc patří do jara?", ["duben", "srpen", "prosinec"], 0),
      choice("Co potřebuje rostlina k růstu?", ["vodu, světlo a půdu", "jen stín", "jen kameny"], 0),
      choice("Co uděláš před přechodem silnice?", ["rozběhnu se bez rozhlédnutí", "rozhlédnu se a přejdu opatrně", "zavřu oči"], 1),
      choice("Jaké číslo voláme na hasiče?", ["150", "155", "158"], 0),
      choice("K čemu slouží nos?", ["ke čichání", "k psaní", "ke kreslení"], 0),
      choice("V kterém ročním období z mnoha stromů opadává listí?", ["na jaře", "v létě", "na podzim"], 2),
      choice("Jak se jmenuje den po úterý?", ["pondělí", "středa", "neděle"], 1),
      choice("Kde vychází slunce?", ["na východě", "na severu", "na západě"], 0),
      choice("Do které nádoby obvykle třídíme papír?", ["do modré", "do žluté", "do zelené"], 0),
      choice("Co je zdravá snídaně?", ["bonbony", "jogurt s ovocem", "brambůrky"], 1),
      choice("Kdo pomáhá nemocným lidem?", ["lékař", "pekař", "zahradník"], 0),
      choice("Které zvíře často hlídá dům a bydlí v boudě?", ["pes", "kapr", "slepice"], 0),
      choice("Který dopravní prostředek jezdí po kolejích?", ["vlak", "loď", "autobus"], 0),
      choice("Který měsíc patří do léta?", ["leden", "červenec", "listopad"], 1),
      choice("Čím si myjeme ruce, aby byly čisté?", ["barvou", "vodou a mýdlem", "pískem"], 1),
      choice("K čemu slouží mapa?", ["k vaření", "k orientaci", "k uspávání"], 1),
      choice("Co si obvykle vezmeme v zimě na ruce?", ["rukavice", "plavky", "sandály"], 0),
      choice("Jak se jmenuje mládě krávy?", ["hříbě", "tele", "štěně"], 1),
      choice("Který strom má jehličí?", ["smrk", "jabloň", "bříza"], 0),
      choice("Které dny tvoří víkend?", ["úterý a středa", "sobota a neděle", "čtvrtek a pátek"], 1),
      choice("Proč jsou včely užitečné?", ["opylují květy", "vypínají slunce", "přesouvají hory"], 0),
      choice("Co patří do lékárničky?", ["obvaz", "kostky lega", "píšťalka"], 0),
      choice("K čemu slouží kořeny rostliny?", ["přijímají vodu z půdy", "zpívají", "svítí"], 0),
      choice("Co je státní symbol České republiky?", ["vlajka", "ponožka", "polštář"], 0),
      choice("Co je nejlepší udělat při silné bouřce venku?", ["stoupnout si pod osamělý strom", "schovat se do bezpečí", "běhat po poli"], 1),
      choice("Jak se máme chovat v lese?", ["křičet a lámat větve", "odhazovat odpadky", "tiše a ohleduplně"], 2),
      choice("Jak se jmenuje nejbližší hvězda k Zemi?", ["Měsíc", "Slunce", "Mars"], 1),
      choice("Co vzniká, když něco zastaví světlo?", ["stín", "duha", "vítr"], 0),
      choice("Ve které místnosti doma obvykle spíme?", ["v ložnici", "v garáži", "ve sklepě"], 0),
      choice("Kolik dní má jeden týden?", ["5", "7", "10"], 1),
      choice("Který orgán pumpuje krev do těla?", ["žaludek", "srdce", "ucho"], 1),
      choice("V kterém ročním období se často sklízí obilí?", ["v létě", "v zimě", "na jaře"], 0),
      choice("Proč se poutáme v autě?", ["abychom byli v bezpečí", "aby auto jelo rychleji", "aby bylo v autě teplo"], 0),
      choice("Který materiál bývá v okně a je průhledný?", ["dřevo", "sklo", "hlína"], 1),
      choice("Co je Země?", ["hvězda", "planeta", "kometa"], 1),
      choice("Proč nesbíráme neznámé houby?", ["mohou být jedovaté", "protože jsou z papíru", "protože létají"], 0),
      choice("Co se stane s vodou při velkém mrazu?", ["zmrzne", "začne hořet", "změní se v kámen"], 0),
      choice("Kdo doručuje dopisy a balíčky?", ["pošťák", "pilot", "číšník"], 0),
      choice("Po které straně silnice jde chodec, když není chodník?", ["po levé", "po pravé", "uprostřed"], 0),
      choice("Co ukazuje kompas?", ["výšku stromu", "světové strany", "teplotu vody"], 1),
      choice("Proč třídíme odpad?", ["aby se dal lépe recyklovat", "aby zmizel sám", "aby byl těžší"], 0),
      choice("Co dělají listy rostlin?", ["pomáhají rostlině vyrábět živiny", "mění se v kameny", "schovávají déšť"], 0),
      choice("Co člověk potřebuje každý den, aby byl zdravý?", ["jen bonbony", "pití, jídlo a spánek", "jen televizi"], 1),
      choice("Jak se jmenuje voda, která padá z mraků v kapkách?", ["sníh", "déšť", "mlha"], 1),
      choice("Proč je dobré znát číslo 112?", ["je to tísňová linka pomoci", "je to číslo na počasí", "je to číslo na kino"], 0),
    ],
  },
  matematika: {
    title: "Matematika pro 3. třídu",
    subtitle: "Počítání od lehkých příkladů po slovní úlohy",
    description: "50 otázek s výběrem ze tří možností. Postupně tě čekají těžší úkoly.",
    type: "choice",
    questions: [
      choice("Kolik je 3 + 4?", ["6", "7", "8"], 1),
      choice("Kolik je 10 - 6?", ["4", "5", "6"], 0),
      choice("Kolik je 5 + 2?", ["6", "7", "9"], 1),
      choice("Kolik je 8 - 3?", ["4", "5", "6"], 1),
      choice("Kolik je 2 + 9?", ["11", "12", "10"], 0),
      choice("Kolik je 12 - 5?", ["6", "7", "8"], 1),
      choice("Kolik je 6 + 7?", ["12", "13", "14"], 1),
      choice("Kolik je 14 - 8?", ["5", "6", "7"], 1),
      choice("Kolik je 9 + 8?", ["16", "17", "18"], 1),
      choice("Kolik je 15 - 7?", ["7", "8", "9"], 1),
      choice("Kolik je 4 × 3?", ["12", "10", "14"], 0),
      choice("Kolik je 12 : 3?", ["3", "4", "5"], 1),
      choice("Kolik je 5 × 6?", ["25", "30", "35"], 1),
      choice("Kolik je 18 : 2?", ["8", "9", "10"], 1),
      choice("Kolik je 7 × 4?", ["24", "28", "32"], 1),
      choice("Kolik je 24 : 6?", ["3", "4", "5"], 1),
      choice("Kolik je 9 × 3?", ["27", "21", "24"], 0),
      choice("Kolik je 32 : 4?", ["6", "7", "8"], 2),
      choice("Kolik je 6 × 7?", ["36", "42", "48"], 1),
      choice("Kolik je 40 : 5?", ["7", "8", "9"], 1),
      choice("Které číslo je o 1 větší než 59?", ["58", "60", "69"], 1),
      choice("Které číslo je o 10 menší než 84?", ["74", "64", "94"], 0),
      choice("Kolik je 27 + 15?", ["41", "42", "43"], 1),
      choice("Kolik je 54 - 19?", ["35", "34", "36"], 0),
      choice("Kolik je 36 + 28?", ["62", "64", "66"], 1),
      choice("Kolik je 70 - 26?", ["44", "46", "48"], 0),
      choice("Kolik je 8 × 8?", ["56", "64", "72"], 1),
      choice("Kolik je 45 : 5?", ["8", "9", "10"], 1),
      choice("Jaký je obvod čtverce se stranou 4 cm?", ["12 cm", "16 cm", "8 cm"], 1),
      choice("Jaký je obvod obdélníku se stranami 5 cm a 3 cm?", ["15 cm", "16 cm", "18 cm"], 1),
      choice("Kolik je polovina z 18?", ["8", "9", "10"], 1),
      choice("Které číslo má 3 desítky a 7 jednotek?", ["73", "37", "307"], 1),
      choice("Kolik centimetrů jsou 2 metry?", ["20 cm", "200 cm", "2000 cm"], 1),
      choice("Kolik minut je 1 hodina a 15 minut?", ["65", "75", "85"], 1),
      choice("Kolik je 4 × 9 - 5?", ["31", "36", "41"], 0),
      choice("Kolik je 7 + 8 + 9?", ["22", "24", "26"], 1),
      choice("Kolik je 63 : 7 + 4?", ["11", "12", "13"], 2),
      choice("Jana měla 18 jablek a 5 snědla. Kolik jí zbylo?", ["12", "13", "14"], 1),
      choice("V knihovně je 6 polic a na každé 8 knih. Kolik je tam knih?", ["42", "48", "54"], 1),
      choice("Kolik je 100 - 37?", ["63", "67", "73"], 0),
      choice("Kolik je 48 + 27 - 10?", ["63", "64", "65"], 2),
      choice("Kolik je 6 × 6 + 8?", ["42", "44", "46"], 1),
      choice("Jaké číslo doplníš místo čtverečku? □ + 17 = 42", ["24", "25", "26"], 1),
      choice("Pět krabic má v každé 8 pastelek. Kolik pastelek je dohromady?", ["35", "40", "45"], 1),
      choice("Kolik je 72 : 8?", ["8", "9", "10"], 1),
      choice("Jaké číslo pokračuje v řadě 5, 10, 15, ...?", ["18", "20", "25"], 1),
      choice("Které číslo je sudé?", ["23", "34", "45"], 1),
      choice("Kolik desítek je v čísle 90?", ["8", "9", "10"], 1),
      choice("Hračka stojí 35 Kč. Máš 50 Kč. Kolik korun ti zbyde?", ["10 Kč", "15 Kč", "20 Kč"], 1),
      choice("Autobus přivezl 28 dětí, dalších 17 přistoupilo a 9 vystoupilo. Kolik dětí zůstalo v autobuse?", ["34", "36", "38"], 1),
    ],
  },
  cestina: {
    title: "Čeština pro 3. třídu",
    subtitle: "Slova, věty a základy gramatiky",
    description: "50 otázek od jednoduchého poznávání slov až po těžší jazykové úkoly.",
    type: "choice",
    questions: [
      choice("Které slovo je podstatné jméno?", ["dům", "běží", "veselý"], 0),
      choice("Které slovo je sloveso?", ["stůl", "běží", "malý"], 1),
      choice("Které slovo je přídavné jméno?", ["veselý", "pes", "skáče"], 0),
      choice("Čím začíná věta?", ["malým písmenem", "velkým písmenem", "číslem"], 1),
      choice("Co píšeme na konci otázky?", ["tečku", "vykřičník", "otazník"], 2),
      choice("Co často píšeme na konci rozkazu?", ["vykřičník", "čárku", "dvojtečku"], 0),
      choice("Jaké je opačné slovo ke slovu malý?", ["krátký", "velký", "slabý"], 1),
      choice("Jak zní množné číslo od slova kočka?", ["kočky", "kočkai", "kočkové"], 0),
      choice("Kolik slabik má slovo okno?", ["1", "2", "3"], 1),
      choice("Které slovo je napsané správně?", ["škola", "škkola", "skola"], 0),
      choice("Které slovo je vlastní jméno?", ["Praha", "město", "ulice"], 0),
      choice("Které slovo označuje osobu?", ["učitel", "strom", "sešit"], 0),
      choice("Která věta je napsaná správně?", ["pes běží po zahradě.", "Pes běží po zahradě.", "Pes Běží po zahradě."], 1),
      choice("Které slovo se rýmuje se slovem les?", ["pes", "most", "vlak"], 0),
      choice("Které slovo má tři slabiky?", ["les", "malina", "strom"], 1),
      choice("Co ve větě hledáme otázkami Kdo? Co?", ["podmět", "otazník", "abecedu"], 0),
      choice("Co nám ve větě říká přísudek?", ["jakou má věta barvu", "co někdo dělá", "kolik je hodin"], 1),
      choice("Které slovo je v jednotném čísle?", ["strom", "stromy", "listy"], 0),
      choice("Které slovo je v množném čísle?", ["kniha", "okno", "stromy"], 2),
      choice("Která věta je oznamovací?", ["Kde je aktovka?", "Dnes svítí slunce.", "Ukliď si pokoj!"], 1),
      choice("Která věta je tázací?", ["Kde máš aktovku?", "Polož knihu na stůl.", "Dnes prší."], 0),
      choice("Která věta je rozkazovací?", ["Zítra pojedeme na výlet.", "Ukliď si pokoj!", "Kdo přišel?"], 1),
      choice("Které slovo je synonymem ke slovu hezký?", ["krásný", "smutný", "těžký"], 0),
      choice("Které slovo je opak ke slovu rychle?", ["pomalu", "rychlík", "hlasitě"], 0),
      choice("Kolik písmen má slovo slunce?", ["5", "6", "7"], 1),
      choice("Které slovo obsahuje dlouhou samohlásku?", ["mísa", "les", "dom"], 0),
      choice("Která slova jsou v abecedním pořadí?", ["les, auto, dům", "auto, dům, les", "dům, auto, les"], 1),
      choice("Jak správně rozdělíme slovo kočička na slabiky?", ["ko-čič-ka", "koč-ič-ka", "ko-či-čka"], 0),
      choice("Které slovo patří do stejné slovní rodiny jako les?", ["lesník", "střecha", "tráva"], 0),
      choice("Které slovo je zdrobnělina?", ["dům", "domeček", "domov"], 1),
      choice("Které slovo je základní tvar slovesa?", ["psát", "psal", "psali"], 0),
      choice("Ve větě „Maminka vaří oběd.“ je podmět:", ["vaří", "maminka", "oběd"], 1),
      choice("Ve větě „Pes štěká.“ je přísudek:", ["pes", "štěká", "je"], 1),
      choice("Která věta obsahuje výčet se správnou čárkou?", ["V batohu mám sešit penál a svačinu.", "V batohu mám sešit, penál a svačinu.", "V batohu mám, sešit penál a svačinu."], 1),
      choice("Které slovo je obecné jméno?", ["Česko", "Eva", "město"], 2),
      choice("Které slovo je jméno osoby?", ["pes", "Eva", "školka"], 1),
      choice("Která věta má správný pořádek slov?", ["Pojedeme zítra na výlet.", "Na zítra pojedeme výlet.", "Výlet pojedeme na zítra."], 0),
      choice("Které slovo je citoslovce?", ["bác", "sešit", "modrý"], 0),
      choice("Které slovo označuje vlastnost?", ["hodný", "běží", "míč"], 0),
      choice("Které slovo je příbuzné ke slovu voda?", ["vodník", "jablko", "kopec"], 0),
      choice("Která věta je napsaná bez chyby?", ["V neděli jedeme k babičce.", "v neděli jedeme k babičce.", "V neděli Jedeme k babičce."], 0),
      choice("Které slovo patří mezi zájmena?", ["já", "malý", "škola"], 0),
      choice("Které slovo může nahradit jméno Petr ve větě?", ["on", "my", "ty"], 0),
      choice("Které slovo je spojka?", ["a", "pod", "velký"], 0),
      choice("Které slovo je předložka?", ["pod", "běží", "ona"], 0),
      choice("Která věta má správnou interpunkci?", ["Ahoj babičko!", "Ahoj, babičko!", "Ahoj babičko!,"], 1),
      choice("V jakém pořadí jsou správně slova podle abecedy?", ["hruška, jahoda, jablko", "hruška, jablko, jahoda", "jahoda, hruška, jablko"], 1),
      choice("Které slovo má čtyři slabiky?", ["ko-lo-běž-ka", "strom", "mrak"], 0),
      choice("Které slovo je nadřazené slovům jablko, hruška, švestka?", ["zahrada", "ovoce", "strom"], 1),
      choice("Která věta je napsaná správně s velkým písmenem?", ["moje kamarádka bydlí v Brně.", "Moje kamarádka bydlí v Brně.", "Moje kamarádka bydlí v brně."], 1),
    ],
  },
  "vyjmenovana-slova": {
    title: "Vyjmenovaná slova pro 3. třídu",
    subtitle: "Trénink i/y hravou formou",
    description: "50 otázek od jednodušších doplňovaček po těžší slova příbuzná.",
    type: "choice",
    questions: [
      choice("Anežka ___dlí ve Spořicích.", ["bydlí", "bidlí", "bydly"], 0),
      choice("Na louce roste zelená ___lina.", ["bilina", "bylina", "bylyna"], 1),
      choice("Na farmě mají silného ___.", ["bíka", "býka", "bijka"], 1),
      choice("V pokoji máme nový ___.", ["nábytek", "nábitek", "nábydek"], 0),
      choice("Každý ___ domu musí dodržovat pravidla.", ["obivatel", "obyvatel", "obývatel"], 1),
      choice("Kůň a kráva patří mezi ___.", ["dobitek", "dobytek", "dobytekh"], 1),
      choice("Ptáček si staví malý ___.", ["příbitek", "přibytek", "příbytek"], 2),
      choice("Sokol má velmi ___ zrak.", ["bistrý", "bystrý", "bystří"], 1),
      choice("Na pastvině běžela hnědá ___.", ["kobila", "kobyla", "kobíla"], 1),
      choice("Každé ráno máme stejný ___.", ["običej", "obyčej", "obýčej"], 1),
      choice("V zimě jezdíme na ___.", ["ližích", "lyžích", "lížích"], 1),
      choice("Po běhu mě bolelo ___.", ["lítko", "lýtko", "lytko"], 1),
      choice("Mouka se dřív mlela v ___.", ["mlýně", "mlině", "mlýne"], 0),
      choice("Jídlo máme dobře rozkousat a ne rychle ___.", ["polikat", "polykat", "políkat"], 1),
      choice("V domě nesmí unikat ___.", ["plin", "plyn", "plýn"], 1),
      choice("Z chodby bylo ___ zvonek.", ["slišet", "slyšet", "slýšet"], 1),
      choice("Nemáme zbytečně ___ jídlem.", ["plítvat", "plýtvat", "plitvat"], 1),
      choice("Kdo nemá vlasy, je ___.", ["lisý", "lysý", "lýsý"], 1),
      choice("Na starém kameni rostl ___.", ["lišejník", "lyšejník", "lyšejnik"], 1),
      choice("Pod kůrou stromu je ___.", ["líko", "lýko", "lyko"], 1),
      choice("Na stole leží voňavé ___.", ["mídlo", "mýdlo", "mydlo"], 1),
      choice("Pod skříní se schovala malá ___.", ["myš", "mýš", "miš"], 0),
      choice("V létě kolem květin létá ___.", ["hmis", "hmyz", "hmys"], 1),
      choice("Auto se nesmí v myčce jen tak ___ vodou.", ["mít", "mýt", "myt"], 1),
      choice("V jednoduchém příkladu se nechci ___.", ["mýlit", "milit", "mílit"], 0),
      choice("Když odcházíme, musíme ___ dveře.", ["zamikat", "zamykat", "zamíkat"], 1),
      choice("Po dešti lezl po chodníku ___.", ["hlemížď", "hlemýžď", "hlemižď"], 1),
      choice("Z peřiny vyletělo jemné ___.", ["chmíří", "chmýří", "chmyří"], 1),
      choice("Vítr začal ___ do ohně.", ["dmýchat", "dmíchat", "dmychat"], 0),
      choice("Krásné město ___ leží v Česku.", ["Litomišl", "Litomyšl", "Lytomyšl"], 1),
      choice("Brambory neseme v ___.", ["pitli", "pytli", "pitly"], 1),
      choice("Pes ukázal zuby a horní ___.", ["pisk", "pysk", "pýsk"], 1),
      choice("Květina má na tyčinkách žlutý ___.", ["pil", "pyl", "píl"], 1),
      choice("V noci létá ___.", ["netopír", "netopýr", "netopyr"], 1),
      choice("Kůň má tvrdé ___.", ["kopito", "kopýto", "kopyto"], 2),
      choice("Na louce roste plevel jménem ___.", ["pír", "pyr", "pýr"], 2),
      choice("Voda se na slunci krásně ___.", ["třpití", "třpytí", "třpitý"], 1),
      choice("Není hezké mít velkou ___.", ["píchu", "pychu", "pýchu"], 2),
      choice("Na schodech se nesmí ___.", ["klopítat", "klopýtat", "klopytat"], 1),
      choice("Ve škole se učíme český ___.", ["jazik", "jazyk", "jazík"], 1),
      choice("K svačině máme chléb a ___.", ["sír", "sýr", "syr"], 1),
      choice("Na krmítko přiletěla ___.", ["síkora", "sýkora", "sykora"], 1),
      choice("Do misky budeme ___ zrní.", ["sipat", "sypat", "sípát"], 1),
      choice("Po dobrém obědě jsem úplně ___.", ["sitý", "sytý", "sity"], 1),
      choice("Mrkev chutná dobře i ___.", ["syrová", "sirová", "sýrová"], 0),
      choice("Had umí hlasitě ___.", ["sičet", "syčet", "sytět"], 1),
      choice("Maminka má jednoho ___.", ["sina", "syna", "sýna"], 1),
      choice("V lese večer houkal ___.", ["výr", "vír", "vyr"], 0),
      choice("Dospělým lidem máme ___ a být slušní.", ["vykat", "vikat", "výkat"], 0),
      choice("Na zastávku musíme přijít ___.", ["brzi", "brzy", "brzí"], 1),
    ],
  },
  anglictina: {
    title: "Angličtina pro 3. třídu",
    subtitle: "Napiš anglické slovo do textového pole",
    description: "Uvidíš české slovo a napíšeš jeho anglický překlad. Celkem 50 otázek.",
    type: "text",
    questions: [
      textQuestion("pes", ["dog"]),
      textQuestion("kočka", ["cat"]),
      textQuestion("dům", ["house"]),
      textQuestion("sešit", ["notebook"]),
      textQuestion("kniha", ["book"]),
      textQuestion("jablko", ["apple"]),
      textQuestion("voda", ["water"]),
      textQuestion("mléko", ["milk"]),
      textQuestion("slunce", ["sun"]),
      textQuestion("měsíc", ["moon"]),
      textQuestion("máma", ["mum", "mom", "mother"]),
      textQuestion("táta", ["dad", "father"]),
      textQuestion("bratr", ["brother"]),
      textQuestion("sestra", ["sister"]),
      textQuestion("kamarád", ["friend"]),
      textQuestion("škola", ["school"]),
      textQuestion("učitel", ["teacher"]),
      textQuestion("pero", ["pen"]),
      textQuestion("tužka", ["pencil"]),
      textQuestion("stůl", ["table"]),
      textQuestion("židle", ["chair"]),
      textQuestion("okno", ["window"]),
      textQuestion("dveře", ["door"]),
      textQuestion("červená", ["red"]),
      textQuestion("modrá", ["blue"]),
      textQuestion("zelená", ["green"]),
      textQuestion("žlutá", ["yellow"]),
      textQuestion("černá", ["black"]),
      textQuestion("bílá", ["white"]),
      textQuestion("jedna", ["one"]),
      textQuestion("dva", ["two"]),
      textQuestion("tři", ["three"]),
      textQuestion("čtyři", ["four"]),
      textQuestion("pět", ["five"]),
      textQuestion("hlava", ["head"]),
      textQuestion("ruka", ["hand"]),
      textQuestion("noha", ["leg"]),
      textQuestion("oko", ["eye"]),
      textQuestion("ucho", ["ear"]),
      textQuestion("nos", ["nose"]),
      textQuestion("ústa", ["mouth"]),
      textQuestion("chléb", ["bread"]),
      textQuestion("sýr", ["cheese"]),
      textQuestion("auto", ["car"]),
      textQuestion("vlak", ["train"]),
      textQuestion("kolo", ["bike", "bicycle"]),
      textQuestion("běžet", ["run"]),
      textQuestion("číst", ["read"]),
      textQuestion("psát", ["write"]),
      textQuestion("hrát si", ["play"]),
    ],
  },
};
